import "./globals.css";
import Header from "@/component/header";
import { Bebas_Neue } from 'next/font/google';
import DefaultView from "@/component/defaultLayout";

const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bebas',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
